### ISSUE TITLE
Heisenbug - hang disappears if I import this library

### ISSUE THREAD

**Issue by kevinburke** [mafintosh/why-is-node-running#41] opened 2018-10-03 21:18 UTC
I'm trying to debug an issue where sending SIGINT to the running process results in a hang - the process refuses to exit.

However, the mere act of adding a `require` for this library causes the issue to disappear.

The actual hang is somewhere in a mess of webpack-serve, webpack-dev-middleware, webpack, and something called thread-loader.

Do you have any hypotheses for why that could happen?

**Comment by kevinburke** [comment] 2018-10-03 21:20
Specifically if I import this library - the process *always* exits with a write EPIPE or "This socket has been ended by the other party," presumably between a thread-loader WorkerPool communicating with its children. If I do not import this library it exits with one of those errors 15% of the time and hangs ~85% of the time.

**Comment by jonkoops** [comment] 2024-07-09 20:03
I don't think this is reproducible any longer, nor do I know how we would even start diagnosing it considering it would need a large stack to reproduce. Since the specific issue was fixed under https://github.com/webpack-contrib/thread-loader/issues/33 I think we can go ahead an close this. If anyone has a reproducible use-case feel free to log a new issue.

**Closed by jonkoops** 2024-07-09 20:03 UTC
